### PR TITLE
The last row of transformation matrix is redundant

### PR DESCRIPTION
**Pull request by TianyiShi2001**
The last row of a transformation matrix is always `[0,0,0,1]` and thus can be removed.

### CODE REVIEW

**Comment by TianyiShi2001** [comment]
As far as I'm concerned all affine transformations does not modify the last row in the transformation matrix and this row is only modified when making a projection (from a higher dimensional object)

**Comment by TianyiShi2001** [comment]
By the way, it's usually more performant to collapse matrices into arrays (in this case, collapsing `[[f64; 4]; 3]` into `[f64; 12]`), and this technique is used, for example in [imageproc](https://github.com/image-rs/imageproc/blob/master/src/geometric_transformations.rs)

**Comment by nonnominandus** [comment]
I agree. I also agree with the single array thing but would like to see some benchmarks first, as I could not find any online. I need to resolve some conflicts so I will do that later.

**Comment by TianyiShi2001** [comment]
Conflicts solved. Could you merge this PR and I'll open another PR regarding collapsing the matrix. (the cargo clippy warnings will also be dealt with in another PR)

**Comment by nonnominandus** [comment]
I will do that.

**Pull request merged**
